# Meta Data for SEO

## Homepage
title = "BCA Notes"
titleSeparator = "-"
titleAddition = "Get your notes"
description = "Get your BCA notes in one place. Whether you're studying for a test or need to make up an assignment, at BCA Notes we have the course notes and study guides you need."


# ## Open Graph + Twitter Cards
# images = ["doks.png"]
# twitterSite = "henkverlinde"
# twitterCreator = "henkverlinde"
# facebookAuthor = "verlinde.henk"
# facebookPublisher = "verlinde.henk"
# ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaGitHub = "https://github.com/xvishaldongre/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Made with ❤ by Vishal Dongre"

# Alert
alert = false
alertText = "Like BCA Notes? <a class=\"alert-link\" href=\"https://github.com/xvishaldongre/xvishaldongre.github.io/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/xvishaldongre/xvishaldongre.github.io/"
editPage = true
